name: Forecast
description: "App by SonBaoKhang"
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  connectivity_plus: ^6.0.3
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.11.0
  http: ^1.3.0
  intl: ^0.19.0
  material_color_utilities: 0.11.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  translator: ^1.0.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "assets/icons/ic_launcher_adaptive_back.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/weather/

  # Fonts have been taken from fonts.google.com
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
